//Trigger : ->
//sense event : edge sensitive blocking @(), level sensitive non blocking wait()

module tb;
//the data generated by the generator needs to be sent to driver where we require IPC
//similar the data recieved by the monitor needs to be sent to scoreboard where we require IPC
    event a;

    initial begin
        #10;
        //trigger an event
        -> a;
    end

    initial begin
        //@(a);
        wait(a.triggered);
        $display("Received Event at %0t", $time);
    end

endmodule